apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgDQezwQss/9H0P1ci1qAG2OQtM8T0i3earMKvRRO624zffWnzDJXFq403+MgESsqgStnymypEPN/f1zuswwlX40sZxtgk1So0bhZtix4wMG1JIuhZ9BneZCgQmfAQBvUG5kOeFtSlGU5kIZSSJV5QjvCfn5YB5Em8Cw6WsBPLVJLcHtUzTpPTJgL/Bo+qh5tQ1yyeTJO4bpLsI+G2Pxg3Dvw9BUoqc1kyhi/ieBQ9BTKFijlz92Sqhzq/SCm+baHybI5ok2qDrAphElcVO3CrmAcc8XfvvuPg4jpM8H2tORC3gOYomR8zGtdnrSQJOFegyid0kZOP2JEFG7jHA0QYoKOvHecFyrVo0Tit8IaJl8DZ3jWuNpigM2qzgid+nTfj+T5Er7h9g5hiaWEV12x5OlpC3I+DySEaKmCNjCLtoyW21HiR0mRIb34lEvIpO+o7WgQpf/EuA72bnZWxbBzwsinzBcPDRjNo/lGpO+t6solcRHtfjtycl1SWA3/S8qRqWjIEDyApRr3ttX62Z6N3VseCM2+dzpIGneOQbsrF2S7JuBKZDuq50q4UvDp3fNYvPXhuRwSnzpTtmtl/jLdlYIlYh6imO79Xew/0SFd085lHqpngbLKHe+p/+pHpe94QkPC5UvaPaDBm6/+0KLoEzWTQrrP7G0484qLRXZ6f2DLSUe2SAzOmCNtZaXIv9NSooe1eKWBMxgNaxciKobzS0T1qEvLCATVe6p
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

